version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: udacity-reverseproxy
  backend_user:
    build:
      context: ../../udacity-restapi-user
    image: udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-restapi-feed
    image: udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-frontend
    image: udacity-frontend:prod
